### ISSUE TITLE
where is train.txt and val.txt ?

### ISSUE THREAD

**Issue by cqlouis** [nikhilroxtomar/MKDCNet#1]
I can not find the train.txt and val.txt in train.py  as below:
```
def load_data(path):
    train_names_path = f"{path}/train.txt"
    valid_names_path = f"{path}/val.txt"
```

Thanks!

**Comment by nikhilroxtomar** [comment]
I have uploaded both files (train.txt and val.txt) to the folder named `dataset` in the repository.
